### ISSUE TITLE
Failed to extract AssetData/boot/Firmware/Manifests/InstallerBoot/* from update bundle The bless of the installer disk failed.

### ISSUE THREAD

**Issue by snowdream** [ninxsoft/Mist#115]
### :beetle: Description
Create macOS Ventura 13.6.2 ISO on macOS Monterey 12.7.2

```
An error has occurred!

Invalid Termination Status: 250

Copying essential files...
Copying the macOS RecoveryOS...
Making disk bootable...


Erasing disk: 0%... 10%... 20%... 30%... 100%
Failed to extract AssetData/boot/Firmware/Manifests/InstallerBoot/* from update bundle
The bless of the installer disk failed.
```

Describe clearly and concisely what is not working.

### :clipboard: Steps to Reproduce

1. Open `Mist.app`
1. Click on 'Installers' - 'macOS Ventura 13.6.2'
1. Wait for Creating ISO
1. Observe error

### :white_check_mark: Expected Behaviour

Describe what should be happening (ie. the happy path).
macOS Ventura 13.6.2 ISO Created.

### :computer: Environment

- Mist version (App menu ⇨ **About Mist**): **0.9.1**
- macOS Version (`sw_vers`): **VERSION BUILD**
- Hardware (`system_profiler SPHardwareDataType`):
  - Model Identifier: **MODEL_IDENTIFIER**
  - Chip : **CHIP**

### :camera: Screenshots

If applicable, add screenshots to help explain the bug.

<img width="586" alt="image" src="https://github.com/ninxsoft/Mist/assets/737958/7e91642e-5422-43a7-a2be-d79923b35296">

<img width="420" alt="image" src="https://github.com/ninxsoft/Mist/assets/737958/47e68cab-a81a-424e-b8c1-e50f0661d4dd">

<img width="260" alt="image" src="https://github.com/ninxsoft/Mist/assets/737958/fb147a17-4a49-471c-a519-f517f579980c">

### :information_source: Additional context

- Is this also a bug in [mist-cli](https://github.com/ninxsoft/mist-cli)? :white_check_mark: / :x:
  - Provide links to GitHub Issues
- Links to 3rd-party tools / references / documentation

**Comment by ninxsoft** [comment]
@snowdream this is because both available builds of **macOS Ventura 13.6.2** installers are tied to specific hardware:

**22G2321:**
- iMac (24-inch, 2023)
- MacBook Pro (14-inch, M3, Nov 2023)

**22G320:**
- MacBook Pro (14-inch, 2021)
- MacBook Pro (16-inch, 2021)
- MacBook Pro (14-inch, 2023)
- MacBook Pro (16-inch, 2023)

In contrast, a compatible build of **22G513** generates an ISO without issue:

![22G513](https://github.com/ninxsoft/Mist/assets/4812595/773f4c1b-52cc-4528-aaa0-68f8577f62fc)

Building ISOs etc. requires that specific hardware in order to succeed. You can hide incompatible versions by checking the **Only show compatible versions** checkbox in the bottom section of the main window:

![Compatible](https://github.com/ninxsoft/Mist/assets/4812595/4e3a1601-5121-4d31-8e71-992e1e130c71)
