### ISSUE TITLE
THIS CREATES A LOGIN ITEM WITH NINDI GILL!!!

### ISSUE THREAD

**Issue by Frankie24** [ninxsoft/Mist#127]
This MIST tool is creating a login item with "Nindi Gill" This needs to change. This is causing an issue.

**Comment by kevinmcox** [comment]
Nindi Gill is the developer of Mist and thus the tool is signed with his Apple Developer Certificate.

This is expected behavior and not a bug.

**Comment by PicoMitchell** [comment]
For independent developers, it is simple to create a developer account as an individual and this will always have the developers name as the signing identity.

To have the signing identity be a company/organization name, the developer account has to be made as an organization which has a lot more overhead and legal requirements that tend to put that option out of reach for small independent developers who are publishing their passion/side projects for free or open source (like Mist is).

More info: https://developer.apple.com/programs/enroll/

To be blunt, the issue here is an education issue on your end. The signing identity being the developers name is not unprofessional nor is it hacky or indictive of any vulnerability. Showing the developers name may give you pause, but with a little research you can understand why this is the way it is (which is Apple's decision) and you can also research the developer listed to see if you feel they are to be trusted. In this case I personally consider Nindi Gill to be a trusted individual in the Mac development community.

**Comment by BigMacAdmin** [comment]
Deleting or uninstalling LaunchDaemons is also a standard macOS knowledge issue. In this case, the simplest way to get it off your background items list is to remove the app and remove this file `/Library/LaunchDaemons/com.ninxsoft.mist.helper.plist` and reboot

And next time, rather than getting all twisted about standard macOS behavior, maybe think twice before putting in your administrator password when prompted. The app had to ask you to authenticate to get that Daemon in place. You approved it without researching or understanding what it was. You're just lucky this was a reputable app/developer and not actual malware.

**Comment by PicoMitchell** [comment]
A individual developer account does not have the ability or choice to change their developer signing identity name. It will always be the person's name. To have a business name, that requires the business/organization name where the name you choose must be an established legal entity name and has all those associated legal hoops to jump through.

**Comment by PicoMitchell** [comment]
That all being said, I believe it should be possible to get the LaunchDaemon to show the "Mist" app name rather than the signing identity. Hopefully Nindi may be able to get that sorted.
