### ISSUE TITLE
Make the implications of using custom seed SUCatalogs more obvious

### ISSUE THREAD

**Issue by Coros** [ninxsoft/Mist#14]
macOS 12.6.1 has not yet released.  It is in Beta 3 at this time.  I see it in Mist v0.3 

<img width="480" alt="Screen Shot 2022-10-12 at 1 38 59 PM" src="https://user-images.githubusercontent.com/17457045/195422454-eca47fd3-a294-4565-b667-c104baa1bc9a.png">

**Comment by Z1mDMan** [comment]
This got me confused as well, for some reason it's not being flagged as beta so I think that's why it shows up without "Include Betas" checked.

**Comment by ninxsoft** [comment]
A macOS Installer is currently deemed a beta if the build number ends in a lowercase letter:

https://github.com/ninxsoft/Mist/blob/3a79a93c11851ed44d7aab2625d90b8388077eed/Mist/Model/Installer.swift#L156-L158

This would explain why build `21G215` is showing up as non-beta, which makes sense as it's a Release Candidate / RC.

As far as the macOS Installers that show up in Mist are concerned, that all depends on the Software Update Catalogs (SUCatalog) being provided by Apple. If Apple add these builds to the SUCatalogs, the macOS Installers will show up in Mist. 👍

**Comment by BigMacAdmin** [comment]
Re-upping this, because it caused confusion amongst my team this week.

12.6.2 is showing up in Mist v.3.0 even when "Include Betas" isn't selected.

Is it on the roadmap to somehow clarify this in the UI? Currently it's easy to make a mistake and download a pre-release macOS unintentionally. 

<img width="485" alt="image" src="https://user-images.githubusercontent.com/106293503/204104814-67b3a6c2-3b81-41ac-9434-eee33b69a415.png">

**Comment by JoGilb** [comment]
@BigMacAdmin @ninxsoft 
I unfortunately overlooked this misleading information, downloaded and installed 12.6.2 on some devices. What's now my fallback path? At no point on any screens during the install or after, it is mentioned it is a beta or a RC version. I really appreciate your efforts making tools like Mist or MDS (that embeds Mist), but arguing it's because of the SUcatalog provided by Apple is not a a valid reason. I thought tools like Mist or MDS would take that flaw from Apple into consideration and warn accordingly that 12.6.2 is not officially released and lists 12.6.2 clearly as a RC version. Glad to hear your views on this. Thank you.

**Comment by kevinmcox** [comment]
@JoGilb At the end of the day, free and open source tools like Mist are created in people's free time. They are shared because the developer hopes they will be helpful to others, but that doesn't create any obligation on their part.

It is our responsibility as MacAdmins to make sure we are aware of the choices we are making when it comes to downloading and installing software. It is our responsibility to know which versions of macOS are current and which are beta, not depend on a tool such as Mist to tell us.

The great part about open source software is that anyone can contribute. Anyone is welcome to make edits to the code to fix issues like this and submit a PR for the benefit of everyone. If a developer working in their spare time isn't moving fast enough for you then feel free to fix the issue yourself and give back to the community.

**Comment by JoGilb** [comment]
@kevinmcox 
Thank you for your comment. I will then try to put my contribution.

In the meantime, I will turn to more reliable tools that properly give a more realistic view of what's considered as Production items, for instance SUS Inspector (@hjuutilainen) which inspects Apple Server Catalogs, like Mist does.

SUS Inspector currently doesn't list Monterey 12.6.2. And I wanted to understand why.
 
I am not a developer but an end-user. However I did a bit of comparison between Mist and SUS Inspector. 
Correct me if I am wrong. Here are the defaults catalogs read by these 2 tools.

Mist
https://swscan.apple.com/content/catalogs/others/index-12customerseed-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
https://swscan.apple.com/content/catalogs/others/index-12seed-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.suctalog.gz
https://swscan.apple.com/content/catalogs/others/index-12beta-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz

SUS Inspector
https://swscan.apple.com/content/catalogs/others/index-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog
https://swscan.apple.com/content/catalogs/others/index-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz
https://swscan.apple.com/content/catalogs/others/index-12-10.16-10.15-10.14-10.13-10.12-10.11-10.10-10.9-mountainlion-lion-snowleopard-leopard.merged-1.sucatalog.gz

As you can notice, the only common piece between Mist ans SUS Inspector is the last catalog listed.
So it sounds that Monterey 12.6.2 comes out in Mist either from index-12customerseed, or index-12seed, or index-12beta catalogs. Given the names of these 3 catalogs, it doesn't seem to be considered as a Production one.

So this is definitely misleading in Mist. Because the MDS tool (from twocanoes.com) embeds Mist, there is an issue also in MDS because by selecting the Production catalog in MDS, Monterey 12.6.2 is shown when it must not.

index-12customerseed, or index-12seed, or index-12beta catalogs are not deemed to be Production catalogs. The issue is not coming out from Apple.

<img width="781" alt="screenshot" src="https://user-images.githubusercontent.com/101991717/205585756-f22f135f-bedb-42d9-bdb8-0c93b0256aac.png">

Hope this helps as my contribution. And again correct me if I am wrong. I am not a developer.

**Comment by ninxsoft** [comment]
@JoGilb thanks for chipping in with the research - I want to provide my thoughts and then a couple of options to move forward.

I previously wrote:

> A macOS Installer is currently deemed a beta if the build number ends in a lowercase letter:
> 
> https://github.com/ninxsoft/Mist/blob/3a79a93c11851ed44d7aab2625d90b8388077eed/Mist/Model/Installer.swift#L156-L158
> 
> This would explain why build `21G215` is showing up as non-beta, which makes sense as it's a Release Candidate / RC.
> 
> As far as the macOS Installers that show up in Mist are concerned, that all depends on the Software Update Catalogs (SUCatalog) being provided by Apple. If Apple add these builds to the SUCatalogs, the macOS Installers will show up in Mist 👍

I believe this information still holds true. Just because something is / is not in a specific SUCatalog does not determine if it is beta or not. The build numbers determine beta / RC / public release, and Apple decides which SUCatalogs to make these builds available in.

The issue at hand (which @JoGilb was able to ascertain) is that Mist fails to make it obvious that the following SUCatalogs are indexed by default:

* Default macOS SUCatalog
* Customer Seed - AppleSeed Program
* Developer Seed - Apple Developer Program
* Public Seed - Apple Beta Software Program

As you point out in your testing @JoGilb, these SUCatalogs can be modified in the app preferences via the **Installers** tab:

![Preferences](https://user-images.githubusercontent.com/4812595/205616181-0df4fed8-29cb-4d22-a60a-4976e75045a5.png)

Removing the **Customer Seed** / **Developer Seed** / **Public Seed** SUCatalogs and keeping the default yields results omitting **macOS 12.6.2 (21G317)**.

Without any modifications to the code, @Coros / @Z1mDMan / @JoGilb  you have a path forward - simply remove the SUCatalogs that do not apply to your use case.

> I politely make an improvement request: add tick boxes for Production, Seed, CustomerSeed Catalogs close to the Beta one at the bottom of the user interface

I believe adding 4 additional checkboxes will clutter up the main user interface - this feature request would only be for a subset of users that are relying on Mist to help make organisational decisions. Most users / non Mac Admins will not care.

Where we can improve the user experience, and something @BigMacAdmin alluded to, is update the **Installers** tab in the app preferences to make the implications of custom seed SUCatalogs using  a _little_ more obvious. I have something in mind, and will follow up with a proof of concept 🙏

> Hope this helps as my contribution. And again correct me if I am wrong. I am not a developer.

You don't need to be a developer to help contribute - just continue to be respectful and provide constructive feedback / propose solutions 👍

**Comment by ninxsoft** [comment]
> I am an end-user of these tools like Mist or MDS, and yes these tools help make decisions as long as what's been presented in the UI is crystal clear with no possible interpretation. Shiny UI but to be used with caution. May I ask you not to speak for all "most users/non MacAdmins". In this thread we are actually "only" 2-3 users reporting the UI is prone to confusion. But how many have installed 12.6.2 without knowing it is still a non-production version and are in a big mess now? OK for the possible clutter in the interface. Then put them clearly in the Prefs with 3 choices: Production / Beta / Release Candidate.

My apologies, I did not mean to offend. Similar to what @kevinmcox said previously - as the author of Mist, all I can recommend is that I **would not use** Mist solely to determine what version of macOS is available for upgade. At a minimum, consult Apple's documentation (eg. [macOS Release Notes](https://developer.apple.com/documentation/macos-release-notes)).

Mist was originally created to streamline the tedious + manual process of building macOS Installers. It was never designed to be used an authority on production-ready macOS releases. I can however improve the user interface + user experience 🙂

> Sorry to insist with MDS (because Mist is embedded into), but having a dropdown box selector saying Production, then including in response beta and RC versions is really really bad for all non-developer, non-MacAdmin. It is a matter of agreeing on vocabulary. Production means production, no? What else? SUS Inspector is much better as it pulls out only Production stuff.

I am not the author of MDS. You have to understand Mist is [free open-source software](https://en.wikipedia.org/wiki/Free_and_open-source_software) (that I work on in my spare time) that anybody can take and modify / distribute etc. in accordance with the [MIT license](https://github.com/ninxsoft/Mist/blob/main/LICENSE). I recommend speaking to the MDS authors / maintainers about your experience 👍

**Comment by JoGilb** [comment]
I did not mean to offend either. 

I think there's some room for clarity between "never designed to be used as an authority" and having beta/RC releases listed as if they were Production versions. But I am not a developer, I have no clue how long and difficult it is to improve the UI/UX.

As for MDS, point has been raised on Slack twocanoes-mds channel, but no comment so far.

<img width="800" alt="image" src="https://user-images.githubusercontent.com/101991717/205643942-e559a870-627d-41ad-b5e4-a745550082d5.png">

> I can however improve the user interface + user experience

Looking forward to seeing improvements. And thanks again very much for your time and efforts!

**Comment by JoGilb** [comment]
Cluttered, really? 😉

[UI prop.pdf](https://github.com/ninxsoft/Mist/files/10155323/UI.prop.pdf)

Based on the Apple-provided catalogs as per the defaults prefs.
No change needed in the Installer Prefs tab. 
The tick boxes in the frontend allows to see or not what the user wants to get. From my perspective, no confusion.
Add tooltips on mouse hovering to provide better explanation for each of them. 
RC is for Seed and CustomerSeed catalogs to my understanding. I may be wrong.

How can this address display for user-defined (non-Apple) catalogs? Well, I leave that one to you to answer... 😇

**Comment by kevinmcox** [comment]
@JoGilb Coming back to this question from earlier:

> I unfortunately overlooked this misleading information, downloaded and installed 12.6.2 on some devices. What's now my fallback path?

I don't think you should stress about this. 12.6.2 is already a release candidate. You can run the following command on those computers and make sure they are not enrolled in the beta seed:

`sudo /System/Library/PrivateFrameworks/Seeding.framework/Versions/A/Resources/seedutil current`

If they are run this command to unenroll them:

`sudo /System/Library/PrivateFrameworks/Seeding.framework/Versions/A/Resources/seedutil unenroll`

After a couple weeks they'll either be on the current release or see an update to 12.6.2 final if the current RC gets changed again.

**Comment by JoGilb** [comment]
@kevinmcox Thank you!
I will run these commands as soon as I can.

**Comment by ninxsoft** [comment]
Okay, here's where I'm at:

<img width="652" alt="Mist Preferences" src="https://user-images.githubusercontent.com/4812595/206173769-3c54c114-b035-46f6-b8c7-b91eb8c7e3ea.png">

The app preferences will allow you to select which catalogs you wish to search within. **Standard** is selected by default, and new macOS versions will be added every 12 months (most likely in-between WWDC and release).

**Comment by kevinmcox** [comment]
Looks good, the descriptions are very helpful as well.

**Comment by Z1mDMan** [comment]
> Okay, here's where I'm at:
> 
> <img alt="Mist Preferences" width="652" src="https://user-images.githubusercontent.com/4812595/206173769-3c54c114-b035-46f6-b8c7-b91eb8c7e3ea.png">
> 
> The app preferences will allow you to select which catalogs you wish to search within. **Standard** is selected by default, and new macOS versions will be added every 12 months (most likely in-between WWDC and release).

Thanks for all the work you do on this @ninxsoft. Can the catalogs be updated following WWDC? I noticed that 15.0 shows up in mist-cli but not in the GUI version.

**Comment by ninxsoft** [comment]
Hi @Z1mDMan, absolutely! I am just waiting for the macOS Sequoia icon to be made available in the next beta release 😅

Hopefully in the next ~2 weeks 🤞
