### ISSUE TITLE
OS selection is not working right

### ISSUE THREAD

**Issue by JohnnyFireOne** [ninxsoft/Mist#142]
@ninxsoft @parnas

hello! and thank for this awesome and wonderful app!
i may found a bug, when i check sequoia standard and public releases other showed up too in the main app window.
can this be fixed?
![SCR-20240921-pkbu](https://github.com/user-attachments/assets/ac12e696-6c8f-4fff-80e1-34d5ebeb3d98)

**Comment by ninxsoft** [comment]
@JohnnyFireOne this is actually expected behaviour - the Software Update Catalogs contain installer releases for multiple operating systems, and not just operating systems for that individual SUCatalog.

The specific installers will vary from catalog to catalog, but generally speaking, another way of thinking about is:

| **SUCatalog** | **15.x** | **14.x** | **13.x** | **12.x** | **11.x** | **10.15.x** |
| :- | :-: | :-: | :-: | :-: | :-: | :-: |
| **macOS Sequoia** | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **macOS Sonoma** | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **macOS Ventura** | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| **macOS Monterey** | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: | :white_check_mark: |
