### ISSUE TITLE
Detect invalid cache directory permissions + notify / rectify

### ISSUE THREAD

**Issue by hisaac** [ninxsoft/Mist#19]
I just downloaded Mist for the first time to try it out, and I'm having issues when the app is trying to configure the cache directory.

I get this error message whenever I start a download:

<img width="1012" alt="Screenshot 2022-12-05 at 2 35 48 PM" src="https://user-images.githubusercontent.com/923876/205738296-696f8eb6-b186-41d1-9624-bb163263bb3a.png">

Error text:

> **An error has occurred!**
>
> Error: You don't have permission to save the file "061-26589" in the folder "Cache".

I tried giving Mist full disk access, but the issue persists.

Is there something I can do to resolve this on my end?

Info:

- Mist version: 0.3
- macOS Version: 13.0.1 (22A400)
- Processor: Apple Silicon M1

**Comment by kevinmcox** [comment]
Where are you trying to put the cache?

**Comment by hisaac** [comment]
🤷‍♂️ Not sure on that. Is that a configurable setting? I don't remember specifying it.

**Comment by ninxsoft** [comment]
I came across this too recently - definitely confirm Mist has Full Disk Access:

![Full Disk Access](https://user-images.githubusercontent.com/4812595/205758430-21876804-05a4-40a5-b743-c015d42bf839.png)

You can specify your Cache directory in the app preferences, under the **Installers** tab:

![Cache](https://user-images.githubusercontent.com/4812595/205758673-ffe9676d-54f5-4929-a0c4-728d3f9245ea.png)

If you are able to confirm this @hisaac, I'll update the README to help make the setup process clearer 👍

**Comment by hisaac** [comment]
ok, a little more insight after some investigation.

I tried using the CLI tool before I used the GUI, and — assuming that uses the same cache location by default — I think it set the permissions of the directory incorrectly. When I first ran the CLI, it told me I had to run it with `sudo`. When I did that, I bet it created that cache directory with permissions for the super user rather than for my account.

Here's what Get Info shows on that directory:

<img width="377" alt="Screenshot 2022-12-05 at 5 10 17 PM" src="https://user-images.githubusercontent.com/923876/205768032-0dcd81bd-e7b1-41c5-9a3c-ab32624c46e2.png">

I just deleted that `/Users/Shared/Mist` directory, re-ran it from Mist.app, and it made it past that first step just fine.

So perhaps some better error messaging would be useful? If that first step fails, maybe it could say something like, "Ensure you have permissions to write to <cache_dir>".

**Comment by ninxsoft** [comment]
@hisaac thanks for the investigation! The error messages are currently dynamic, essentially the stdout / stderr of the binaries I am running under the hood. I can definitely update the README to reflect better instructions 👍

Another option is to have the ability to fix / reset the cache directory permissions in the app preferences, and to add a check to confirm the cache can be written to before attempting the full download. Since the app uses a PrivilegedHelperTool, Mist can perform tasks that would generally require sudo (ie. fixing directory permissions).

I'll prototype something and get back to you, thanks again from bringing this to my attention 🙌
