### ISSUE TITLE
Add Close Window (with Command+W shortcut) to File menu

### ISSUE THREAD

**Issue by PicoMitchell** [ninxsoft/Mist#24]
Since there is no "Close Window" menu item with the Command+W shortcut in the file menu, trying to use the default Command+W shortcut to close the Preferences/Settings window, or to close the actual Mist window just beeps instead of actually closing the window. Since Command+W is muscle memory for me, it feels confusing/wrong for it to just beep instead of actually closing the frontmost window.

**Comment by ninxsoft** [comment]
Looks like another one-line fix: https://github.com/ninxsoft/Mist/commit/524cf3d105685bd458d7a8ab1d18559c2f7478ca

**Note:** You will not be able to close / hide windows on modals, which I believe is a good, or rather, expected behaviour. Users will be prompted "are you sure?" before returning to the main app window.
