### ISSUE TITLE
Question: About codesigning

### ISSUE THREAD

**Issue by blacktop** [ninxsoft/Mist#44]
My apologies for asking this in an issue:

Can you explain the purpose of `--image-signing-identity` what does codesigning an installer?  Does this allow you to use them offline? (without internet?)

Thank you!

**Comment by ninxsoft** [comment]
No apology necessary!

If you specify the `--image-signing-identity` flag, it codesigns the generated Disk Image (**.dmg**), not the macOS Installer app bundle (**.app**)

It is considered best-practice to codesign generated disk images, especially if you are distributing them. You generally see these GateKeeper warnings when opening applications on non-code signed disk images (ie. that have been downloaded from the web):

![Example](https://user-images.githubusercontent.com/4812595/142786175-4079ad9a-2a5f-4f6a-a4a8-47dd8a64a9c4.png)

Apple has documentation explaining [Signing Disk Images](https://developer.apple.com/library/archive/documentation/Security/Conceptual/CodeSigningGuide/Procedures/Procedures.html#//apple_ref/doc/uid/TP40005929-CH4-SW19)

**Comment by blacktop** [comment]
Ah! Thank you for the response!!  I've been trying to understand if it is possible to create offline macOS installers that work on machines with T2 processors and was hoping that this might be the "trick."

**Comment by PicoMitchell** [comment]
While it is possible to create a USB installer which pre-downloads and includes the T2 firmware rather than downloading it at install time (using `createinstallmedia --downloadassets`), it is not possible to do a fully offline installation for a T2 or Apple Silicon Mac because of a required "personalization" step which is basically a signed record from Apple over the internet approving the installation for the specific computer. This "personalization" step cannot be bypassed or skipped. Internet is just plain required to install macOS on T2 or Apple Silicon Macs.

**Comment by blacktop** [comment]
Thank you!!
