### ISSUE TITLE
Request: Check if sudo privilege elevation is required for Apple Silicon

### ISSUE THREAD

**Issue by carlashley** [ninxsoft/Mist#48]
I'm wondering if `sudo` privilege elevation is actually required for the Apple Silicon files given it's just a download of an IPSW file?

This could probably be removed for this specific platform.

**Comment by ninxsoft** [comment]
Although you currently require `sudo` privileges to download IPSW files, this is not a hard requirement (it's a holdover from the `sudo` requirement for installing packages to generate the `.app` bundles).

Will look at removing this requirement.

**Note:** You will require the correct directory permissions to save the IPSW file otherwise `mist` will throw an error.
