### ISSUE TITLE
Can't create Ventura 13.4 USB installer with createinstallmedia

### ISSUE THREAD

**Issue by jaffacakerhubarb** [ninxsoft/Mist#52]
### :beetle: Description

I've used Mist quite a few times to download various macOS installers, and then I have a USB stick with a few separate partitions to install whichever via the createinstallmedia command. I've used this for all including Ventura with no issues previously. However, Ventura 13.4 fails on the createinstallmedia command. I redownloaded a couple of times, initially with Mist 0.7 and again with 0.7.1. I know this could easily be an Apple bug rather than any fault of Mist, but perhaps the logs might illuminate the problem?

### :clipboard: Steps to Reproduce

1. Open Mist
2. Download Ventura (13.4, 22F2073) for Intel
3. Once completed downloading (green ticks all the way), use the usual createinstallmedia command via Terminal to make a bootable USB installer

### :white_check_mark: Expected Behaviour

I should end up with an intel USB installer for 13.4.

### :computer: Environment

- Mist version (0.7.1)
- macOS Version (12.6.6, but have also tried with a Mac running Ventura 13.4)
- Hardware (Mac mini 2014)

### :camera: Logs from Terminal

```
REDACTED@REDACTED ~ % sudo /Users/REDACTED/Documents/macOS\ installers/\(13.4\)\ Install\ macOS\ Ventura\ 13.4_22F2073.app/Contents/Resources/createinstallmedia --volume /Volumes/ventura

Password:
Ready to start.
To continue we need to erase the volume at /Volumes/ventura.
If you wish to continue type (Y) then press return: y
Erasing disk: 0%... 10%... 20%... 30%... 100%
Copying essential files...
Copying the macOS RecoveryOS...
Making disk bootable...
Failed to extract AssetData/boot/Firmware/Manifests/InstallerBoot/* from update bundle
The bless of the installer disk failed.

```

**Comment by ninxsoft** [comment]
macOS Ventura 13.4 build **22F2073** is *technically* a custom build for the newly released Mac Studio, Mac Pro and 15-inch MacBook Air, so YMMV when attempting to run on unsupported hardware.

Are you having the same issue with build **22F66**?

You can also check the **Only show compatible versions** option on the bottom of the window to hide truly unsupported versions on the Mac you are running 👍

![Screenshot 2023-06-12 at 10 32 37 pm](https://github.com/ninxsoft/Mist/assets/4812595/fc50d907-0a0a-459a-99a7-93d739a05266)

**Comment by jaffacakerhubarb** [comment]
Aha! You are spot on. Either the custom build came a little before the full 13.4 installer became available, or I just missed it as I'm not used to seeing two of the same version in the list. I downloaded **22F66** as you advised and everything worked exactly as expected.

The Mac I'm on only goes up to Monterey, so ticking that box would leave Ventura out entirely for me, otherwise your suggestion is very sensible. Is there any way to identify these custom builds somehow as distinct from the standard builds?

It's odd that they would have an Intel build for that custom version, given that all those new Mac models are Apple Silicon only. I guess a custom build is a custom build, perhaps they've deliberately omitted certain assets in the Intel version to flag it up to careless people like me!

Thank you very much!

**Comment by ninxsoft** [comment]
**Slight clarification:** Installers are not just for Intel:

- macOS Installers for macOS Catalina 10.15 and older are for Intel based Macs only
- macOS Installers for macOS Big Sur 11 and newer are Universal - for both Apple Silicon and Intel based Macs

Having said that, I have long term plans to add support for iOS / iPadOS / tvOS etc., which offer separate firmwares for each hardware model. This will most likely mean Mist will be re-built from the ground up to display a list of hardware models first, and when you select a model, you only see the list of available firmwares / installers (negating the need for that compatibility checkbox).

We have been getting away with that compatibility checkbox up until now because each macOS firmware / installer supports multiple hardware models, but this may change in the future as Apple introduces new hardware and/or I add more functionality to Mist 👍
