### ISSUE TITLE
When downloading macOS installers, convert .ipsw to .dmg

### ISSUE THREAD

**Issue by tempusthales** [ninxsoft/Mist#68]
Currently Mist downloads an ipsw file.  It would be nice it did the conversion to a .dmg automatically

**Comment by PicoMitchell** [comment]
I'm curious what scenario you would want an IPSW to be within a DMG for?

**Comment by ninxsoft** [comment]
Ditto, @tempusthales what is your use case for wrapping the IPSW inside a DMG?

**Comment by tempusthales** [comment]
I don't want to wrap the .IPSW into a DMG, I want to convert the .ipsw into a dmg, so it can be more programatically friendly to get it deployed on the endpoint.

I'm assuming this is possible, since there are other tools like [installinstallmacos.py](https://github.com/grahampugh/macadmin-scripts/blob/main/installinstallmacos.py) that do it.

**Comment by PicoMitchell** [comment]
IPSWs cannot be converted to DMGs (they are actually just ZIP files). IPSWs are also never deployed to an endpoint directly. They used in Apple Configurator 2 on a Mac (the host) to install macOS onto another Apple Silicon that is in DFU Mode and connected to the host Mac with a USB cable: https://support.apple.com/en-il/guide/apple-configurator-mac/apdd5f3c75ad/mac

I think you're thinking of working with macOS Installer Apps (not IPSWs) since `installinstallmacos.py` doesn't download or handle IPSWs at all.

When downloading macOS Installer Apps with `mist`, you can wrap the app in a dmg using the `--image` option (which is what `installinstallmacos.py` does).

**Comment by brianhm** [comment]
Am I understanding then that a full installer cannot be downloaded for Apple Silicon Macs through Mist?  I'm not 100% clear on this from the docs or help.  I can use softwareupdate --fetchfullinstaller to download the full installer on an M1 Mac.  Is this not equivalent here?

**Comment by PicoMitchell** [comment]
The full installer apps for Big Sur and newer downloaded through `mist` are Universal apps that are fully compatible with Intel and Apple Silicon.

The option names used in mist were previously a bit unclear (https://github.com/ninxsoft/Mist/issues/54), but that has since been changed.

**Comment by brianhm** [comment]
Thanks for clarifying.  The homepage of the Github that has all of the examples should be updated then, as it seems to indicate that the installers downloaded via Mist are Intel only.

**Comment by PicoMitchell** [comment]
That is true. Many of the comments for example commands do say "for Intel Macs" for downloads that are Universal. Also the Features list separates things by "For Intel based Macs:" and "For Apple Silicon Macs:" when it should indicate that the apps are Universal for Big Sur and newer.

**Comment by ninxsoft** [comment]
100% agree, I can circle back and make the README + `mist --help` descriptions more obvious!
