### ISSUE TITLE
macOS Big Sur 11.0.1 - 11.3.1 ipsw files fail to download "Invalid download resume data"

### ISSUE THREAD

**Issue by F1248** [ninxsoft/Mist#70]
### :beetle: Description

All macOS Big Sur ipsw files from version 11.0.1 to 11.3.1 fail to download.
However, all versions from 11.4 onwards work.
"An error has occurred! Invalid download resume data"

### :clipboard: Steps to Reproduce

1. Open Mist
2. Wait for refreshing
3. Try to download any ipws file up to and including macOS Big Sur 11.3.1.
4. "An error has occurred! Invalid download resume data“

### :computer: Environment

- Mist version: **0.9**
- macOS Version: **13.4.1 22F82**
- Hardware:
  - Model: **MacBook Air M1**
  - Model Identifier: **MacBookAir10,1**
  - Chip: **Apple M1**

### :camera: Screenshots

<img width="592" alt="Bildschirmfoto 2023-07-02 um 17 48 35" src="https://github.com/ninxsoft/Mist/assets/132580749/18f409be-b155-4822-955b-55958821de96">

**Comment by ninxsoft** [comment]
@F1248 the error message is a little misleading - essentially the issue is an invalid download URL.

For example, the [IPSW.me API](https://ipsw.me) (used to retrieve Firmware metadata) reports back the following URL for **macOS Big Sur 11.0.1 (20B29)**:

- http://updates-http.cdn-apple.com/2020FallFCS/fullrestores/001-79706/93A4C43C-2B45-47AF-84EA-794F8886B85C/UniversalMac_11.0.1_20B29_Restore.ipsw

This is a HTTP URL, which is inaccessible (by design) due to [App Transport Security](https://developer.apple.com/documentation/security/preventing_insecure_network_connections).

The easy fix is to convert these HTTP URLs to valid HTTPS ones, for example:

- https://updates.cdn-apple.com/2020FallFCS/fullrestores/001-79706/93A4C43C-2B45-47AF-84EA-794F8886B85C/UniversalMac_11.0.1_20B29_Restore.ipsw

Replacing `http://updates-http.cdn-apple.com` with `https://updates.cdn-apple.com` dynamically should be enough to fix this issue.

Will keep you posted 👍

**Comment by ninxsoft** [comment]
Easy fix: https://github.com/ninxsoft/Mist/pull/73
