### ISSUE TITLE
Downloads aren't cancelled by pressing Esc, but are finished in the background

### ISSUE THREAD

**Issue by F1248** [ninxsoft/Mist#71]
### :beetle: Description

Downloads aren't cancelled by pressing `Esc`, they are finished in the background, you come back to the Mist home page. From the home page you can start further downloads, if more than one are running at the same time, they will all fail. If Mist is quit or restarted, all downloads are aborted completely.

### :clipboard: Steps to Reproduce

1. Open Mist
2. Wait for refreshing
3. Start downloading anything
4. Press `Esc`, you will return to the Mist home page
5. Monitor the downloaded data volume via Activity Monitor or with [Stats](https://github.com/exelban/stats)
6. Although caching was disabled in the Mist settings, the unfinished file appears in the selected cache directory

### :computer: Environment

- Mist version: **0.9**
- macOS Version: **13.4.1 22F82**
- Hardware:
  - Model: **MacBook Air M1**
  - Model Identifier: **MacBookAir10,1**
  - Chip: **Apple M1**

**Comment by ninxsoft** [comment]
@F1248 great catch! I have been able to replicate this issue.

The quick and easy way to fix this bug is to add the `.interactiveDismissDisabled()` modifier to the **"Activity"** sheet view, preventing dismissal via the escape key:

https://developer.apple.com/documentation/swiftui/view/interactivedismissdisabled(_:)

I will try to investigate if there is a way to prompt the user when the escape key is pressed, much like pressing the **Cancel** button (ie. the user is asked if they want to indeed cancel). Ultimately I feel this will be a better user experience.

Thanks again, will let you know if I make any progress 👍

**Comment by ninxsoft** [comment]
Well that wasn't too painful, 2-3 lines of code 😅

https://github.com/ninxsoft/Mist/pull/72
