### ISSUE TITLE
macOS 13.0 beta installer download failed with error

### ISSUE THREAD

**Issue by iresh-filewave** [ninxsoft/Mist#9]
I am trying to download macOS 13.0 beta with Mist v0.2 and got following error:
`Invalid Termination Status '246': /Volumes/Install macOS Ventura beta is not large enough for install media. An additional 213.2 MB is needed.`
<img width="592" alt="error_mist" src="https://user-images.githubusercontent.com/106729606/190709154-f15d47eb-c031-461a-b9e6-228d479328f8.png">

**Comment by trodemaster** [comment]
Related https://github.com/ninxsoft/mist-cli/issues/102

**Comment by ninxsoft** [comment]
@iresh-filewave thanks for bringing this to my attention - this was fixed in the [mist-cli](https://github.com.ninxsoft/mist-cli) project but the same logic was not translated across to this Mist GUI project.

The fix has now been applied: a48e3a7e2a40abe787b54d99579f89b059ea07a8

And a new release will be made available shortly reflecting this change 👍
